---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-api
  template:
    metadata:
      labels:
        app: app-api
    spec:
      containers:
        - name: app-api
          image: forsebekacr.azurecr.io/task-tracker-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
