---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: application
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: govtechsg/fluentd-elasticsearch:latest
          env:
            - name: FLUENTD_ARGS
              value: --no-supervisor -q
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: config-volume
              mountPath: /fluentd/etc
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: config-volume
          configMap:
            name: fluentd-config
