---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: application
data:
  fluent.conf: |-
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>
    <match **>
      @type elasticsearch
      @log_level info
      host elasticsearch
      port 9200
      logstash_format true
      logstash_prefix fluentd
      include_tag_key true
      type_name _doc  <!-- Ensure compatibility with Elasticsearch 7.x and above -->
    </match>
