---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: application
spec:
  capacity:
    storage: 1Gi
  accessModes: [ReadWriteOnce]
  hostPath:
    path: /mnt/data/postgres
