---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-email-sender
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-email-sender
  template:
    metadata:
      labels:
        app: app-email-sender
    spec:
      containers:
        - name: app-email-sender
          image: forsebek.azurecr.io/task-tracker-email-sender
          envFrom:
            - configMapRef:
                name: app-config
