---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-scheduler
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-scheduler
  template:
    metadata:
      labels:
        app: app-scheduler
    spec:
      containers:
        - name: app-scheduler
          image: forsebekacr.azurecr.io/task-tracker-scheduler
          envFrom:
            - configMapRef:
                name: app-config
