---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: scheduler
          image: forsebek.azurecr.io/task-tracker-scheduler:latest
          envFrom:
            - configMapRef:
                name: app-config
